import {TimerEngine,normalizeConfig,quickStarts,TYPES} from './engine.js';
import {TimerAudio,defaults} from './audio.js';
import {TimerStorage,PresetService} from './storage.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=ms=>{if(!Number.isFinite(ms))return '∞';const s=Math.ceil(Math.max(0,ms)/1000);return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;};
const button=(action,label,extra='')=>`<button type="button" data-timer-action="${action}" ${extra}>${label}</button>`;
export function createWorkoutTimer({root,getContext,notify=()=>{}}){
 let storage,audio,service,userId,config=normalizeConfig(),engine,interval,wakeLock,presets=[],personal=[],favorites=[],history=[],view='home',centralId=null,lastSave=0,lastPhase='',summaryRecorded=false;
 const active=()=>engine&&!['IDLE','FINISHED'].includes(engine.state);
 const persist=()=>{if(engine&&storage){if(!storage.set('active',engine.serialize())&&lastSave===0)notify('Browser-Speicher nicht verfügbar. Wiederherstellung ist nicht möglich.',true);lastSave=Date.now();}};
 async function lock(){if(!active()||document.visibilityState!=='visible'||!navigator.wakeLock)return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>wakeLock=null);}catch{/* Browser may deny on low battery. */}}
 function release(){wakeLock?.release().catch(()=>{});wakeLock=null;}
 function saveLocal(){storage.set('personal',personal);storage.set('favorites',favorites);storage.set('history',history);}
 async function loadCentral(){try{presets=(await service.list()).map(c=>normalizeConfig(c));storage.set('central',presets);if(view==='home')render();}catch{notify('Gemeinsame Timer-Presets konnten nicht geladen werden. Gespeicherte Presets bleiben nutzbar.',true);}}
 function sync(){const context=getContext();const id=context.userId;if(id&&userId&&id!==userId){persist();release();clearInterval(interval);engine=null;view='home';}if(!id){if(userId){release();clearInterval(interval);engine=null;userId=null;document.body.classList.remove('timer-coaching');root.innerHTML='';}return;}if(id===userId)return;
  userId=id;storage=new TimerStorage(id);audio=new TimerAudio(storage.get('settings',defaults));service=new PresetService(context.client);personal=storage.get('personal',[]);favorites=storage.get('favorites',[]);history=storage.get('history',[]);presets=storage.get('central',[]);
  const saved=storage.get('active',null);if(saved&&!['FINISHED','IDLE'].includes(saved.state)){try{engine=TimerEngine.restore(saved,{onEvent:event=>audio.play(event.type)});config=engine.config;view='recovery';}catch{storage.remove('active');}}
  render();loadCentral();
 }
 function card(c){return `<article class="timer-preset"><div><strong>${escape(c.name)}</strong><span>${escape(c.type.replace('_',' '))} · ${description(c)}</span></div><div>${button('preview','Öffnen',`data-id="${escape(c.id)}"`)}${button('favorite',favorites.includes(c.id)?'★':'☆',`data-id="${escape(c.id)}" aria-label="Favorit umschalten"`)}</div></article>`;}
 function description(c){if(['INTERVAL','TABATA'].includes(c.type))return `${c.workDuration}/${c.restDuration} s · ${c.rounds} Runden · ${c.sets} Sets`;return c.type==='CUSTOM'?`${c.blocks.length} Blöcke`:c.type==='FOR_TIME'?c.timeCap?`Cap ${time(c.timeCap*1000)}`:'Ohne Cap':time(c.totalDuration*1000);}
 function field(key,label,value,min=0,max=86400){return `<label>${label}<input name="${key}" type="number" min="${min}" max="${max}" step="1" value="${escape(value)}" required></label>`;}
 function fields(c,prefix='') {const f=(key,label,min=0,max=86400)=>field(prefix+key,label,c[key],min,max);
  if(['INTERVAL','TABATA'].includes(c.type))return f('workDuration','Work · Sekunden',1)+f('restDuration','Rest · Sekunden')+f('rounds','Runden',1,1000)+f('sets','Sets',1,100)+f('setRest','Set-Pause · Sekunden');
  if(c.type==='FOR_TIME')return f('timeCap','Time Cap · Sekunden (0 = offen)');
  if(c.type==='EMOM')return f('totalDuration','Dauer · Sekunden',1)+`<label>Übungen pro Minute · eine je Zeile<textarea name="${prefix}exercises">${escape(c.exercises.join('\n'))}</textarea></label>`;
  if(c.type!=='CUSTOM')return f('totalDuration','Dauer · Sekunden',1);return '';
 }
 function form(){return `<form id="timerConfigForm"><div class="timer-grid"><label>Workout-Name<input name="name" value="${escape(config.name)}" maxlength="120" required></label><label>Modus<select name="type">${TYPES.map(t=>`<option ${config.type===t?'selected':''}>${t}</option>`).join('')}</select></label>${fields(config)}<label>Start-Countdown<select name="precount">${[0,3,5,10,15,30].map(n=>`<option value="${n}" ${config.precount===n?'selected':''}>${n?n+' Sekunden':'Aus'}</option>`).join('')}</select></label></div>${config.type==='CUSTOM'?`<p>Blöcke laufen automatisch nacheinander. For Time ohne Cap endet über „Finish / Block beenden“.</p><div class="timer-blocks">${config.blocks.map((b,i)=>`<fieldset><legend>Block ${i+1}</legend><div class="timer-grid"><label>Name<input name="b${i}.name" value="${escape(b.name)}" required></label><label>Typ<select name="b${i}.type" data-block="${i}">${['TIMER','INTERVAL','EMOM','AMRAP','FOR_TIME','REST','CUSTOM_BLOCK'].map(t=>`<option ${b.type===t?'selected':''} value="${t}">${t==='INTERVAL'?'WORK / REST':t.replace('_',' ')}</option>`).join('')}</select></label>${fields(b,`b${i}.`)}</div><div class="timer-actions">${button('block-up','↑ Nach oben',`data-index="${i}" ${i===0?'disabled':''}`)}${button('block-down','↓ Nach unten',`data-index="${i}" ${i===config.blocks.length-1?'disabled':''}`)}${button('block-copy','Duplizieren',`data-index="${i}"`)}${button('block-delete','Entfernen',`data-index="${i}"`)}</div></fieldset>`).join('')}</div>${button('block-add','+ Block hinzufügen')}`:''}<div class="timer-actions"><button type="submit" class="primary">Workout-Vorschau</button>${button('save','Persönlich speichern')}${getContext().isAdmin?button('central-save',centralId?'Zentrales Preset aktualisieren':'Als BEATFIELD Preset speichern'):''}</div></form>`;}
 function readForm(){const form=root.querySelector('form');if(!form)return config;if(!form.reportValidity())throw Error('Bitte alle Felder prüfen.');const data=new FormData(form),copy=structuredClone(config);for(const [key,value] of data){const target=key.startsWith('b')&&key.includes('.')?copy.blocks[Number(key.split('.')[0].slice(1))]:copy;const name=key.includes('.')?key.split('.')[1]:key;target[name]=name==='exercises'?value.split('\n').map(v=>v.trim()).filter(Boolean):['name','type'].includes(name)?value:Number(value);}return normalizeConfig(copy);}
 function render(){if(!userId)return;
 document.body.classList.toggle('timer-coaching',view==='coach'&&root.classList.contains('hidden')===false);
 const header=`<div class="timer-heading"><div><p class="eyebrow">CAMPUS · TRAIN. BEAT. REPEAT.</p><h2>Workout Timer</h2></div><div class="timer-actions">${button('home','Übersicht')}${button('settings','Sound & Einstellungen')}</div></div>`;
 if(view==='coach'){renderCoach();return;}
 if(view==='summary'){const duration=(engine.finishedAt-engine.startedAt-engine.elapsed);root.innerHTML=header+`<article class="timer-summary"><p class="eyebrow">${engine.completed?'WORKOUT COMPLETE':'WORKOUT GESTOPPT'}</p><h3>${escape(config.name)}</h3><strong>${time(duration)}</strong><p>${escape(config.type)} · ${config.rounds} Runden · ${config.sets} Sets · ${engine.amrapRounds} gezählte Runden</p><div class="timer-actions">${button('home','Fertig')}${button('start','Wiederholen')}${button('save','Als Preset speichern')}</div></article>`;return;}
 if(view==='recovery'){root.innerHTML=header+`<article class="timer-summary"><h3>Workout wiederherstellen</h3><p>${escape(config.name)} · ${engine.state==='FINISHED'?'Während deiner Abwesenheit beendet':escape(engine.state)}. Die Zeit wurde anhand des gespeicherten Zeitpunkts berechnet.</p>${button('recover','Workout öffnen')}${button('discard','Verwerfen')}</article>`;return;}
 if(view==='edit'){root.innerHTML=header+form();return;}
 if(view==='preview'){root.innerHTML=header+`<article class="timer-summary"><p class="eyebrow">WORKOUT PREVIEW</p><h3>${escape(config.name)}</h3><p>${description(config)}</p><p>${config.precount} Sekunden Start-Countdown</p>${config.type==='CUSTOM'?`<ol>${config.blocks.map(b=>`<li>${escape(b.name)} · ${description(b)}</li>`).join('')}</ol>`:''}<div class="timer-actions">${button('start','START WORKOUT','class="primary"')}${button('edit','Bearbeiten')}${button('save','Als Preset speichern')}${centralId&&getContext().isAdmin?button('central-delete','Zentrales Preset löschen'):''}</div></article>`;return;}
 if(view==='settings'){root.innerHTML=header+`<h3>Sound & Einstellungen</h3><div class="timer-grid">${Object.entries({halfway:'Halbzeitsignal',ten:'10-Sekunden-Warnung',countdown:'3–2–1 Countdown',voice:'Sprachansagen',vibration:'Vibration',start:'Startsignal',finish:'Finish-Signal'}).map(([key,label])=>`<label class="timer-toggle"><input type="checkbox" data-setting="${key}" ${audio.settings[key]?'checked':''}>${label}</label>`).join('')}<label>Timer-Lautstärke <output>${audio.settings.volume}%</output><input type="range" min="0" max="100" value="${audio.settings.volume}" data-setting="volume"></label></div><h3>Audio-Test</h3><div class="timer-actions">${[['halfway','Halbzeit'],['ten','10 Sekunden'],['count3','Countdown'],['work','Work'],['rest','Rest'],['finish','Finish']].map(([tone,label])=>button('test',label,`data-tone="${tone}"`)).join('')}</div><p>Spotify läuft unabhängig. Teste die Signale vor dem Training mit deiner Box. Im Hintergrund oder bei gesperrtem Bildschirm können Browser Audio aussetzen; die Zeitberechnung bleibt korrekt. Halte die Coach-Ansicht sichtbar.</p>`;return;}
 const all=[...quickStarts,...personal,...presets];root.innerHTML=header+`<div class="timer-mode-grid">${TYPES.map(t=>button('mode',t.replace('_',' '),`data-type="${t}"`)).join('')}</div>${active()?`<div class="timer-actions">${button('recover','Laufendes Workout öffnen')}</div>`:''}<h3>Favoriten</h3><div class="timer-preset-grid">${all.filter(c=>favorites.includes(c.id)).map(card).join('')||'<p>Noch keine Favoriten. Markiere ein Preset mit dem Stern.</p>'}</div><h3>Quick Start</h3><div class="timer-preset-grid">${quickStarts.map(card).join('')}</div><h3>BEATFIELD Presets</h3><div class="timer-preset-grid">${presets.map(card).join('')||'<p>Gemeinsame Presets werden geladen.</p>'}</div><h3>Meine Presets</h3><div class="timer-preset-grid">${personal.map(c=>card(c)+button('personal-delete','Preset löschen',`data-id="${escape(c.id)}"`)).join('')||'<p>Speichere deine Workout-Konfiguration als persönliches Preset.</p>'}</div><details class="timer-history"><summary>Letzte Workouts · ${history.length}</summary>${history.map((h,i)=>`<article class="timer-preset"><div><strong>${escape(h.config.name)}</strong><span>${new Date(h.date).toLocaleString('de-DE')} · ${time(h.duration)} · ${h.completed?'Beendet':'Gestoppt'} · ${h.rounds} gezählte Runden</span></div><div class="timer-actions">${button('recent','Vorschau',`data-index="${i}"`)}${button('recent-edit','Bearbeiten',`data-index="${i}"`)}${button('recent-copy','Duplizieren',`data-index="${i}"`)}${button('recent-save','Als Preset speichern',`data-index="${i}"`)}</div></article>`).join('')||'<p>Noch kein Workout gestartet.</p>'}</details>`;
 }
 function renderCoach(){lastPhase='';root.innerHTML=`<div class="timer-coach"><div class="timer-coach-top"><span>${escape(config.name)}</span>${button('big','Vollbild / Big Screen')}</div><div class="timer-phase" aria-live="polite"></div><div class="timer-time" aria-label="Workout-Zeit"></div><p class="timer-round"></p><p class="timer-next"></p><div class="timer-actions timer-main-controls">${button('pause','Pause')}${button('skip','Skip')}${button('finish','Finish / Block beenden')}</div><details><summary>Coach-Steuerung</summary><div class="timer-actions">${[['plus10','+10 Sek.'],['minus10','−10 Sek.'],['plus30','+30 Sek.'],['round-plus','Runde +'],['round-minus','Runde −'],['next-round','Nächste Runde'],['prev-round','Vorherige Runde'],['restart','Neustart'],['stop','Stop']].map(([a,l])=>button(a,l)).join('')}</div></details><p class="timer-audio-warning"></p></div>`;document.body.classList.toggle('timer-coaching',!root.classList.contains('hidden'));update();}
 function update(){if(!engine)return;const s=engine.tick();if(view==='coach'){
  if(s.state==='FINISHED'){record();view='summary';release();clearInterval(interval);storage.remove('active');render();return;}
  const label=s.state==='PAUSED'?'PAUSE':s.phase?.state==='WORK'?s.phase.type.replace('_',' '):s.phase?.label||s.state;
  const phase=root.querySelector('.timer-phase');if(phase&&lastPhase!==`${label}:${s.index}`){phase.textContent=label+(s.phase?.state==='WORK'&&s.phase.label!==s.phase.type?` · ${s.phase.label}`:'');lastPhase=`${label}:${s.index}`;}
  const digits=root.querySelector('.timer-time');if(digits)digits.textContent=time(s.phase?.countUp?s.elapsed:s.remaining);
  root.querySelector('.timer-coach')?.setAttribute('data-phase',s.phase?.state||s.state);
  const rounds=root.querySelector('.timer-round');if(rounds)rounds.textContent=(s.phase?.type==='AMRAP'?`AMRAP · ${s.amrapRounds} Runden geschafft`:s.phase?.type==='FOR_TIME'?'FOR TIME':`Runde ${s.phase?.round||0} / ${s.phase?.rounds||config.rounds} · Set ${s.phase?.set||0} / ${s.phase?.sets||config.sets}`)+(config.type==='CUSTOM'?` · Block ${s.phase.blockIndex+1} / ${config.blocks.length}`:'');
  const next=root.querySelector('.timer-next');if(next)next.textContent=s.next?`NEXT: ${s.next.label} · ${time(s.next.duration)}`:'NEXT: FINISH';const pause=root.querySelector('[data-timer-action="pause"]');if(pause)pause.textContent=s.state==='PAUSED'?'Fortsetzen':'Pause';
  const warning=root.querySelector('.timer-audio-warning');if(warning)warning.textContent=audio.context?.state==='running'?'':'Audio ist ausgesetzt. Tippe auf „Fortsetzen / Pause“, um Audio wieder freizugeben.';
 }if(Date.now()-lastSave>1000&&active())persist();}
 function record(){if(summaryRecorded)return;summaryRecorded=true;history.unshift({config:engine.config,date:engine.startedAt,duration:engine.finishedAt-engine.startedAt-engine.elapsed,completed:engine.completed,rounds:engine.amrapRounds});history=history.slice(0,50);saveLocal();}
 async function start(){if(active()&&!confirm('Laufendes Workout ersetzen?'))return;const ready=await audio.unlock();if(!ready)notify('Audio wird von diesem Browser nicht unterstützt oder ist blockiert.',true);engine=new TimerEngine(config,{onEvent:event=>audio.play(event.type)});summaryRecorded=false;lastPhase='';engine.start();view='coach';render();clearInterval(interval);interval=setInterval(update,100);persist();lock();}
 function save(){config=readForm();const name=prompt('Name des persönlichen Presets',config.name);if(!name?.trim())return;personal.unshift({...config,id:crypto.randomUUID(),name:name.trim().slice(0,120)});saveLocal();notify('Timer-Preset gespeichert.');}
 root.addEventListener('submit',event=>{if(event.target.id!=='timerConfigForm')return;event.preventDefault();try{config=readForm();view='preview';render();}catch(e){notify(e.message,true);}});
 root.addEventListener('change',event=>{try{const t=event.target;if(t.dataset.setting){audio.settings[t.dataset.setting]=t.type==='checkbox'?t.checked:Number(t.value);storage.set('settings',audio.settings);if(t.type==='range')t.parentElement.querySelector('output').textContent=t.value+'%';return;}if(t.name==='type'){config=normalizeConfig({...config,type:t.value,blocks:t.value==='CUSTOM'?(config.blocks.length?config.blocks:[normalizeConfig({type:'TIMER',name:'Warm-up',totalDuration:300})]):[]});render();}else if(t.dataset.block!==undefined){config=readForm();render();}}catch(e){notify(e.message,true);}});
 root.addEventListener('click',async event=>{const target=event.target.closest('[data-timer-action]');if(!target)return;const a=target.dataset.timerAction;try{
 if(a==='home'){if(active()){view='coach';render();return;}view='home';render();}
 else if(a==='settings'){view='settings';render();}
 else if(a==='mode'){if(active()){notify('Beende zuerst das laufende Workout.',true);return;}config=normalizeConfig({type:target.dataset.type,blocks:target.dataset.type==='CUSTOM'?[{type:'TIMER',name:'Warm-up',totalDuration:300}]:[]});centralId=null;view='edit';render();}
 else if(a==='preview'){if(active()){notify('Beende zuerst das laufende Workout.',true);return;}config=normalizeConfig([...quickStarts,...personal,...presets].find(c=>c.id===target.dataset.id));centralId=presets.some(c=>c.id===config.id)?config.id:null;view='preview';render();}
 else if(a==='favorite'){favorites=favorites.includes(target.dataset.id)?favorites.filter(id=>id!==target.dataset.id):[...favorites,target.dataset.id];saveLocal();render();}
 else if(a==='edit'){view='edit';render();}
 else if(a==='start')await start();
 else if(a==='save')save();
 else if(a==='central-save'){config=readForm();target.disabled=true;await service.save(config,centralId);notify('BEATFIELD Preset gespeichert.');await loadCentral();}
 else if(a==='central-delete'){if(confirm('Zentrales Preset löschen?')){await service.remove(centralId);centralId=null;view='home';await loadCentral();render();}}
 else if(a==='personal-delete'){if(confirm('Persönliches Preset löschen?')){personal=personal.filter(c=>c.id!==target.dataset.id);saveLocal();render();}}
 else if(a==='test'){if(!await audio.unlock())throw Error('Audio konnte nicht gestartet werden.');const old=audio.settings;audio.settings={...old,halfway:true,ten:true,countdown:true,start:true,finish:true};audio.play(target.dataset.tone);audio.settings=old;}
 else if(a==='recover'){await audio.unlock();if(engine.state==='FINISHED')record();view=engine.state==='FINISHED'?'summary':'coach';lastPhase='';render();clearInterval(interval);interval=setInterval(update,100);lock();}
 else if(a==='discard'){engine=null;storage.remove('active');view='home';render();}
 else if(a.startsWith('block-')){config=readForm();const i=Number(target.dataset.index);if(a==='block-add')config.blocks.push(normalizeConfig({type:'TIMER',name:'Neuer Block',totalDuration:60}));if(a==='block-copy')config.blocks.splice(i+1,0,structuredClone(config.blocks[i]));if(a==='block-delete'){if(config.blocks.length===1)throw Error('Mindestens ein Block bleibt erforderlich.');config.blocks.splice(i,1);}if(a==='block-up'&&i>0)[config.blocks[i-1],config.blocks[i]]=[config.blocks[i],config.blocks[i-1]];if(a==='block-down'&&i<config.blocks.length-1)[config.blocks[i+1],config.blocks[i]]=[config.blocks[i],config.blocks[i+1]];render();}
 else if(a.startsWith('recent')){if(active()){notify('Beende zuerst das laufende Workout.',true);return;}config=normalizeConfig(history[Number(target.dataset.index)].config);centralId=null;if(a==='recent-copy'){config.name+=' · Kopie';config.id='';}if(a==='recent-save')save();else{view=a==='recent'?'preview':'edit';render();}}
 else if(a==='big'){root.classList.toggle('timer-big');if(!document.fullscreenElement)await root.requestFullscreen?.();else await document.exitFullscreen?.();}
 else if(engine){if(a==='pause'){await audio.unlock();engine.state==='PAUSED'?engine.resume():engine.pause();}if(a==='skip')engine.skip();if(a==='finish')engine.finish();if(a==='plus10')engine.adjust(10);if(a==='minus10')engine.adjust(-10);if(a==='plus30')engine.adjust(30);if(a==='round-plus')engine.round(1);if(a==='round-minus')engine.round(-1);if(a==='next-round')engine.jumpRound(1);if(a==='prev-round')engine.jumpRound(-1);if(a==='restart'&&confirm('Workout neu starten?')){engine.stop();record();await start();}if(a==='stop'&&confirm('Workout stoppen?'))engine.stop();persist();update();}
 }catch(e){notify(e.message||'Timer-Aktion fehlgeschlagen.',true);}finally{if(target.isConnected)target.disabled=false;}});
 document.addEventListener('keydown',event=>{if(view!=='coach'||root.classList.contains('hidden')||event.target.closest('input,textarea,select,[contenteditable="true"]')||event.ctrlKey||event.metaKey||event.altKey)return;const action={' ':'pause',ArrowRight:'skip','+':'plus10','-':'minus10',r:'round-plus',R:'round-plus'}[event.key];if(action){event.preventDefault();root.querySelector(`[data-timer-action="${action}"]`)?.click();}});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){update();lock();}else persist();});window.addEventListener('pagehide',persist);
 new MutationObserver(()=>document.body.classList.toggle('timer-coaching',view==='coach'&&!root.classList.contains('hidden'))).observe(root,{attributes:true,attributeFilter:['class']});
 return {sync,loadWorkout(input){if(active())throw Error('Laufendes Workout zuerst beenden');config=normalizeConfig(input);centralId=null;view='preview';location.hash='#timerPanel';render();}};
}
